name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  dart_rss: ^2.0.1
  http: ^0.13.1 # for load data from web
  url_launcher: ^6.0.2 # for launch any url
  transparent_image: ^2.0.0 # for placeholders
  cached_network_image: ^3.0.0 # for display most images
  flutter_cache_manager: ^3.0.1 # for cached_network_image
  xml: ^5.1.0 # for cached_network_image
  draggable_scrollbar: ^0.1.0 # for announcements scroll
  flutter_linkify: ^5.0.2 # text to links
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  firebase_analytics: ^8.0.1
  provider: ^5.0.0
  duration: ^3.0.6 # print duration for timetable
  dotted_line: ^3.0.0
  hive: ^2.0.4 # db
  hive_flutter: ^1.0.0
  share: ^2.0.1 # share anything
  path_provider: ^2.0.1 # work with storage paths
  quick_actions: ^0.6.0+1 # shortcuts from launcher
  flutter_cached_pdfview: ^0.4.0-nullsafety # for document viewer
  photo_view: ^0.11.1 # for cabinets map
  file_picker: ^3.0.1 # for adding images to announcements
  flutter_multi_formatter: ^2.0.3

flutter_native_splash:
  color: "#E8E8E8"
  image: assets/splash/light.png
  color_dark: "#121212"
  image_dark: assets/splash/dark.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only available for Android 8.0 devices and above

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.1
  flutter_launcher_icons: ^0.9.0 # launcher icons
  flutter_native_splash: ^1.1.7+1 # splash

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VpecIconPack
      fonts:
        - asset: fonts/VpecIconPack.ttf