name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 # https://pub.dev/packages/intl
  webfeed: # https://pub.dev/packages/webfeed
    git: https://github.com/Tembeon/webfeed.git
  http: ^0.13.0 # https://pub.dev/packages/http
  url_launcher: ^6.0.2 # https://pub.dev/packages/url_launcher
  transparent_image: ^2.0.0-nullsafety.0 # https://pub.dev/packages/transparent_image/
  jiffy: ^4.0.0 # https://pub.dev/packages/jiffy
  cached_network_image: ^3.0.0-nullsafety
  flutter_cache_manager: ^3.0.0-nullsafety.1
  xml: ^5.0.2
  draggable_scrollbar: ^0.0.4
  flutter_linkify: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  firebase_core: "^1.0.0"
  firebase_auth: "^1.0.0"
  cloud_firestore: "^1.0.0"
  get: ^3.26.0
  duration: ^2.0.15
  fdottedline: ^1.0.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0

flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only available for Android 8.0 devices and above

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.5
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VEKiconPack
      fonts:
        - asset: fonts/VEKiconPack.ttf