name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.1+12

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dart_rss: ^2.0.1
  http: ^0.13.4 # for load data from web
  url_launcher: ^6.1.2 # for launch any url
  transparent_image: ^2.0.0 # for placeholders
  cached_network_image: ^3.2.1 # for display most images
  flutter_cache_manager: ^3.3.0 # for cached_network_image
  xml: ^5.4.1 # for cached_network_image
  draggable_scrollbar: ^0.1.0 # for announcements scroll
  flutter_linkify: ^5.0.2 # text to links
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  firebase_analytics: ^9.1.8
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  provider: ^6.0.2
  duration: ^3.0.11 # print duration for timetable
  dotted_line: ^3.1.0
  dotted_decoration: ^2.0.0
  r_dotted_line_border: ^0.1.1
  hive: ^2.2.1 # db
  hive_flutter: ^1.1.0
  share_plus: ^4.0.4 # share anything
  path_provider: ^2.0.10 # work with storage paths
  quick_actions: ^0.6.0+11 # shortcuts from launcher
  file_picker: ^4.5.1 # for adding images to announcements
  flutter_multi_formatter: ^2.5.7
  fluro: ^2.0.3
  url_strategy: ^0.2.0
  flutter_markdown: ^0.6.10
  device_info: ^2.0.3
  breakpoint: ^1.2.0
  uc_pdfview: ^0.0.3
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

flutter_native_splash:
  color: "#E8E8E8"
  image: "assets/splash/light.png"
  color_dark: "#121212"
  image_dark: "assets/splash/dark.png"
  android: true
  # ios: true
  web: true
  android_gravity: center
  #ios_content_mode: center
  web_image_mode: center
  android12:
    image: "assets/splash/light.png"
    icon_background_color: "#E8E8E8"
    image_dark: "assets/splash/dark.png"
    icon_background_color_dark: "#121212"


flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only available for Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2 # launcher icons
  flutter_native_splash: ^2.2.0+1 # splash
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  dart_code_metrics: ^4.15.2

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/splash/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VpecIconPack
      fonts:
        - asset: fonts/VpecIconPack.ttf