name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.1+12

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dart_rss: ^2.0.1
  http: ^0.13.4 # for load data from web
  url_launcher: ^6.0.18 # for launch any url
  transparent_image: ^2.0.0 # for placeholders
  cached_network_image: ^3.2.0 # for display most images
  flutter_cache_manager: ^3.3.0 # for cached_network_image
  xml: ^5.3.1 # for cached_network_image
  draggable_scrollbar: ^0.1.0 # for announcements scroll
  flutter_linkify: ^5.0.2 # text to links
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  firebase_analytics: ^9.0.5
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  provider: ^6.0.2
  duration: ^3.0.8 # print duration for timetable
  dotted_line: ^3.1.0
  hive: ^2.0.5 # db
  hive_flutter: ^1.1.0
  share_plus: ^3.0.4 # share anything
  path_provider: ^2.0.8 # work with storage paths
  quick_actions: ^0.6.0+9 # shortcuts from launcher
  file_picker: ^4.3.1 # for adding images to announcements
  flutter_multi_formatter: ^2.5.1
  fluro: ^2.0.3
  url_strategy: ^0.2.0
  flutter_markdown: ^0.6.9
  device_info: ^2.0.3
  breakpoint: ^1.2.0
  uc_pdfview: ^0.0.3
  freezed_annotation: ^1.1.0

flutter_native_splash:
  color: "#E8E8E8"
  image: assets/splash/light.png
  color_dark: "#121212"
  image_dark: assets/splash/dark.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android12: true

flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only available for Android 8.0 devices and above

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2 # launcher icons
  flutter_native_splash: ^1.3.3 # splash
  flutter_lints: ^1.0.4
  freezed: ^1.1.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/splash/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VpecIconPack
      fonts:
        - asset: fonts/VpecIconPack.ttf