name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.1+22

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.0
  firebase_analytics: ^10.2.0
  firebase_messaging: ^14.4.0

  # used in news screen
  dart_rss:
    git:
      url: https://github.com/Tembeon/dart-rss # parse rss
      ref: master

  http: ^0.13.5 # load data from web
  transparent_image: ^2.0.1 # image placeholders

  # used in announcement screen
  path_provider: ^2.0.14 # work with storage paths
  file_picker: ^5.2.9 # adding images to announcements
  zoom_pinch_overlay: ^1.4.1+3

  # used in schedule screen
  r_dotted_line_border: ^0.1.1
  duration: ^3.0.12 # convert Duration to a humanly understandable text

  # used in doc viewer screen
  flutter_markdown: ^0.6.14
  uc_pdfview: ^0.0.3

  # local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # routes
  fluro: ^2.0.5
  url_strategy: ^0.2.0 # removes '#' from a path

  # generators
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

  # other utils
  intl: ^0.18.0 # work with locale
  url_launcher: ^6.1.10 # open urls in external apps
  flutter_linkify: ^5.0.2 # make links in text tappable
  share_plus: ^6.3.2
  cached_network_image: ^3.2.3 # for display most images
  flutter_cache_manager: ^3.3.0 # for cached_network_image
  xml: ^6.2.2 # for cached_network_image
  quick_actions: ^1.0.2 # shortcuts from launcher
  flutter_local_notifications: ^13.0.0
  provider: ^6.0.5
  device_info: ^2.0.3
  breakpoint: ^1.2.0
  animations: ^2.0.7
  mobile_scanner: ^3.2.0 # QR scanner
  permission_handler: ^10.2.0

flutter_native_splash:
  color: "#E8E8E8"
  image: "assets/splash/light.png"
  color_dark: "#121212"
  image_dark: "assets/splash/dark.png"
  android: true
  # ios: true
  web: true
  android_gravity: center
  #ios_content_mode: center
  web_image_mode: center
  android_12:
    image: "assets/splash/light.png"
    icon_background_color: "#E8E8E8"
    image_dark: "assets/splash/dark.png"
    icon_background_color_dark: "#121212"

# app icon in launcher
flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0 # launcher icons
  flutter_native_splash: ^2.2.19 # splash
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/splash/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VpecIconPack
      fonts:
        - asset: fonts/VpecIconPack.ttf

dependency_overrides:
  intl: 0.18.0