name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 # for DateFormat
  webfeed: # for news
    git: https://github.com/Tembeon/webfeed.git
  http: ^0.13.0 # for load data from web
  url_launcher: ^6.0.2 # for launch any url
  transparent_image: ^2.0.0-nullsafety.0 # for placeholders
  jiffy: ^4.0.0 # for russian date localize
  cached_network_image: ^3.0.0-nullsafety # for display most images
  flutter_cache_manager: ^3.0.0-nullsafety.1 # for cached_network_image
  xml: ^5.0.2 # for cached_network_image
  draggable_scrollbar: ^0.0.4 # for announcements scroll
  flutter_linkify: ^5.0.0 # text to links
  flutter_launcher_icons: ^0.9.0 # launcher icons
  firebase_core: "^1.0.0"
  firebase_auth: "^1.0.0"
  cloud_firestore: "^1.0.0"
  get: ^3.26.0 # useful things
  duration: ^2.0.15 # print duration for timetable
  fdottedline: ^1.0.1 # lines for timetable
  hive: ^2.0.0 # db
  hive_flutter: ^1.0.0
  share: ^2.0.1 # share anything
  path_provider: ^2.0.1 # work with storage paths
  flutter_native_splash: ^1.0.3 # splash

flutter_native_splash:
  color: "#E8E8E8"
  image: assets/splash/light.png
  color_dark: "#121212"
  image_dark: assets/splash/dark.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only available for Android 8.0 devices and above

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.5
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VEKiconPack
      fonts:
        - asset: fonts/VEKiconPack.ttf