name: vpec
description: Мобильное приложение для Волгоградского энергетического колледжа

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+15

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # firebase
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.2.18
  firebase_analytics: ^9.1.10
  firebase_messaging: ^11.4.2

  # used in news screen
  dart_rss:
    git: https://github.com/Tembeon/dart-rss # parse rss
  http: ^0.13.4 # load data from web
  transparent_image: ^2.0.0 # image placeholders

  # used in announcements screen
  draggable_scrollbar: ^0.1.0
  path_provider: ^2.0.11 # work with storage paths
  file_picker: ^4.6.1 # adding images to announcements

  # used in schedule screen
  r_dotted_line_border: ^0.1.1
  duration: ^3.0.11 # convert Duration to humanly understandable text

  # used in doc viewer screen
  flutter_markdown: ^0.6.10+2
  uc_pdfview: ^0.0.3

  # local storage
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  # routes
  fluro: ^2.0.3
  url_strategy: ^0.2.0 # removes '#' from path

  # generators
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # other utils
  intl: ^0.17.0 # work with locale
  url_launcher: ^6.1.4 # open urls in external apps
  flutter_linkify: ^5.0.2 # make links in text tappable
  share_plus: ^4.0.7
  cached_network_image: ^3.2.1 # for display most images
  flutter_cache_manager: ^3.3.0 # for cached_network_image
  xml: ^6.1.0 # for cached_network_image
  quick_actions: ^0.6.0+11 # shortcuts from launcher
  flutter_local_notifications: ^9.6.1
  provider: ^6.0.3
  device_info: ^2.0.3
  breakpoint: ^1.2.0

flutter_native_splash:
  color: "#E8E8E8"
  image: "assets/splash/light.png"
  color_dark: "#121212"
  image_dark: "assets/splash/dark.png"
  android: true
  # ios: true
  web: true
  android_gravity: center
  #ios_content_mode: center
  web_image_mode: center
  android12:
    image: "assets/splash/light.png"
    icon_background_color: "#E8E8E8"
    image_dark: "assets/splash/dark.png"
    icon_background_color_dark: "#121212"

# app icon in launcher
flutter_icons:
  image_path: "assets/launcher/ic_launcher_android.png"
  android: true
  adaptive_icon_background: "assets/launcher/ic_launcher_android_background.png" # only Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/ic_launcher_android_foreground.png" # only Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.3 # launcher icons
  flutter_native_splash: ^2.2.3 # splash
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  dart_code_metrics: ^4.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600

    - family: VpecIconPack
      fonts:
        - asset: fonts/VpecIconPack.ttf