name: Build app
on:
  push:
    branches:
      - v*
  pull_request:
    branches:
      - v*
jobs:
  build_android_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: key-android-20220611

      - run: flutter build apk --release --split-per-abi --bundle-sksl-path flutter_01.sksl.json --release

      - uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-signed.apk

      - uses: actions/upload-artifact@v3
        with:
          name: app-arm64-v8
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release-signed.apk

      - uses: actions/upload-artifact@v3
        with:
          name: app-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release-signed.apk

      - uses: actions/upload-artifact@v3
        with:
          name: app-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release-signed.apk