name: Build app
on:
  push:
    branches:
      - github_workflow
  pull_request:
    branches:
      - github_workflow
jobs:
  build_android_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: key-android-20220611
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - run: flutter build appbundle